T: 0.5
algorithm: aagmm
amp: false
batch_size: 64
clip: 0.0
clip_grad: 1.0
crop_ratio: 0.875
data_dir: ./data
dataset: cifar10_w100
ood_fraction: 0.1
dist_backend: nccl
dist_url: tcp://127.0.0.1:10004
ema_m: 0.999
embedding_constraint: 0
embedding_dim: 128

epoch: 1024
eval_batch_size: 256
gpu: None
hard_label: true
img_size: 32
last_layer: linear
layer_decay: 1.0
lr: 0.03
momentum: 0.9
multiprocessing_distributed: false
net: wrn_28_2
net_from_name: false
num_classes: 10
num_eval_iter: 5120
num_labels: 40
num_log_iter: 256
num_train_iter: 1048576
num_workers: 8
optim: SGD
overwrite: true
p_cutoff: 0.95
rank: 0
resume: false
save_dir: ./saved_models/aagmm_cf10w100
save_name: linear0_cifar10_40_1_1.0_8_none
seed: 273230791
thresh_warmup: true
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
uratio: 7
use_cat: true
use_tensorboard: true
use_wandb: false
weight_decay: 0.0005
world_size: 1
neg_pl_threshold: 0.0
