T: 0.5
algorithm: aagmm
amp: false
batch_size: 64
clip: 0.0
clip_grad: 0.0
crop_ratio: 0.875
data_dir: ./data
dataset: cifar100
dist_backend: nccl
dist_url: tcp://127.0.0.1:10001
ema_m: 0.999
embedding_constraint: 0
embedding_dim: 8
epoch: 1024
eval_batch_size: 256
gpu: None
hard_label: true
img_size: 32
last_layer: linear
layer_decay: 1.0
lr: 0.03
momentum: 0.9
multiprocessing_distributed: false
net: wrn_28_2
net_from_name: false
num_classes: 100
num_eval_iter: 5120
num_labels: 400
num_log_iter: 256
num_train_iter: 1048576
num_workers: 8
optim: SGD
overwrite: true
p_cutoff: 0.95
rank: 0
resume: false
save_dir: ./saved_models/classic_cv
save_name: linear_cifar100_400_0_0.0
seed: 3474173998
thresh_warmup: true
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
uratio: 7
use_cat: true
use_tensorboard: true
use_wandb: false
weight_decay: 0.001
world_size: 1
